# Generated by Django 3.0.7 on 2020-07-15 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question",
                    models.TextField(help_text="What would you like to know?"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("FR", "Freshman"),
                            ("SO", "Sophomore"),
                            ("JR", "Junior"),
                            ("SR", "Senior"),
                            ("GR", "Graduate"),
                        ],
                        default="active",
                        max_length=100,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("enquiry", "Enquiry"),
                            ("trouble_shooting", "Trouble Shooting"),
                            ("payment", "Payment"),
                        ],
                        default="enquiry",
                        max_length=350,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
