# Generated by Django 3.0.7 on 2020-07-15 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("in_active", "In Active")],
                default="active",
                max_length=100,
            ),
        ),
    ]
