# Generated by Django 3.0.7 on 2020-07-15 04:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0003_answer"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="question", options={"ordering": ["-created"]},
        ),
        migrations.AddField(
            model_name="answer",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="question",
            name="question",
            field=models.TextField(
                error_messages={
                    "unique": "Hmm, seems this question was already would you like to rephrase?"
                },
                help_text="What would you like to know?",
                unique=True,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="answer", unique_together={("question", "answer")},
        ),
        migrations.AlterOrderWithRespectTo(
            name="answer", order_with_respect_to="question",
        ),
    ]
