# Generated by Django 3.0.7 on 2020-07-15 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0004_auto_20200715_0428"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="question",
            field=models.TextField(
                error_messages={
                    "unique": "Hmm, seems this question was already asked, would you like to rephrase?"
                },
                help_text="What would you like to know?",
                unique=True,
            ),
        ),
    ]
