# Generated by Django 3.0.7 on 2020-07-15 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0007_answer_user"),
    ]

    operations = [
        migrations.DeleteModel(name="Answer",),
    ]
