# Generated by Django 3.0.7 on 2020-07-15 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0008_delete_answer"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
